---
title: "Color Mapping"
author: "Isabella Sadler"
date: "2023-12-11"
output: html_document
---
```{r}
require(tidyverse)

setwd("~/PhD/LakeColor_SpatTem")
YrAvg<-read.csv("2023-11-09_TEMPORAL_yearly_averaged_dWL (1).csv", header=T)

#color for manually created legend
bg.fui = tibble(
  ymin = c(470,475,480,485,489,495,509,530,549,559,564,567,568,569,570,573,575,577,579,581,583),
  ymax = c(475,480,485,489,495,509,530,549,559,564,567,568,569,570,573,575,577,579,581,583,590),
  color = c(
    "#2158bc", "#316dc5", "#327cbb", "#4b80a0", "#568f96", "#6d9298", "#698c86", 
    "#759e72", "#7ba654", "#7dae38", "#94b660","#94b660", "#a5bc76", "#aab86d", 
    "#adb55f", "#a8a965", "#ae9f5c", "#b3a053", "#af8a44", "#a46905", "#9f4d04")
)

site_cols <- YrAvg %>%
  mutate(dWL = round(dWL,0)) #round dWLs
bg.fui<-as.data.frame(bg.fui)

#create column assigning colors to range of dWL values
YrAvg <- YrAvg %>% 
  mutate(col_hex = case_when(dWL <= bg.fui[1,1] & dWL <bg.fui[1,2] ~bg.fui[1,3],
  dWL <=bg.fui[2,1] & dWL <bg.fui[2,2] ~bg.fui[2,3],
  dWL <=bg.fui[3,1] & dWL <bg.fui[3,2] ~bg.fui[3,3]   , 
  dWL <=bg.fui[4,1] & dWL <bg.fui[4,2] ~bg.fui[4,3]   , 
  dWL <=bg.fui[5,1] & dWL <bg.fui[5,2] ~bg.fui[5,3]   , 
  dWL <=bg.fui[6,1] & dWL <bg.fui[6,2] ~bg.fui[6,3]   , 
  dWL <=bg.fui[7,1] & dWL <bg.fui[7,2] ~bg.fui[7,3]   , 
  dWL <=bg.fui[8,1] & dWL <bg.fui[8,2] ~bg.fui[8,3]   , 
  dWL <=bg.fui[9,1] & dWL <bg.fui[9,2] ~bg.fui[9,3]   , 
  dWL <=bg.fui[10,1] & dWL <bg.fui[10,2] ~bg.fui[10,3]   , 
  dWL <=bg.fui[11,1] & dWL <bg.fui[11,2] ~bg.fui[11,3]   , 
  dWL <=bg.fui[12,1] & dWL <bg.fui[12,2] ~bg.fui[12,3]   , 
  dWL <=bg.fui[13,1] & dWL <bg.fui[13,2] ~bg.fui[13,3]   , 
  dWL <=bg.fui[14,1] & dWL <bg.fui[14,2] ~bg.fui[14,3]   , 
  dWL <=bg.fui[15,1] & dWL <bg.fui[15,2] ~bg.fui[15,3]   , 
  dWL <=bg.fui[16,1] & dWL <bg.fui[16,2] ~bg.fui[16,3]   , 
  dWL <=bg.fui[17,1] & dWL <bg.fui[17,2] ~bg.fui[17,3]   , 
  dWL <=bg.fui[18,1] & dWL <bg.fui[18,2] ~bg.fui[18,3]   , 
  dWL <=bg.fui[19,1] & dWL <bg.fui[19,2] ~bg.fui[19,3]   , 
  dWL <=bg.fui[20,1] & dWL <bg.fui[20,2] ~bg.fui[20,3]   , 
  dWL <=bg.fui[21,1] & dWL <bg.fui[21,2] ~bg.fui[21,3] , T~"black"))  


```
```{r}
states <- map_data("state")

Yr1990<- YrAvg %>% 
  filter(year==1990)
Yr2000<- YrAvg %>% 
  filter(year==2000)
Yr2010<- YrAvg %>% 
  filter(year==2010)
Yr2020<- YrAvg %>% 
  filter(year==2020)

map1990<-ggplot(data = Yr1990) + 
  geom_point(data = Yr1990, aes(x = lake_lon_decdeg, y = lake_lat_decdeg), 
             color = Yr1990$col_hex, size = 1) +  # Add points
  scale_fill_distiller( palette="Spectral", direction=1)+
  theme_void()+
  coord_fixed(1.3) +
  geom_polygon(data= states, aes(x = long, y = lat, group = group),
               fill="transparent",color = "black", linewidth=0.5)+
  labs(title = "1990")

map2000<-ggplot(data = Yr2000) + 
  geom_point(data = Yr2000, aes(x = lake_lon_decdeg, y = lake_lat_decdeg), 
             color = Yr2000$col_hex, size = 1) +  # Add points
  scale_fill_distiller( palette="Spectral", direction=1)+
  theme_void()+
  coord_fixed(1.3) +
  geom_polygon(data= states, aes(x = long, y = lat, group = group), 
               fill="transparent",color = "black", linewidth=0.5)+
  labs(title = "2000")

map2010<-ggplot(data = Yr2010) + 
  geom_point(data = Yr2010, aes(x = lake_lon_decdeg, y = lake_lat_decdeg), 
             color = Yr2010$col_hex, size = 1) +  # Add points
  scale_fill_distiller( palette="Spectral", direction=1)+
  theme_void()+
  coord_fixed(1.3) +
  geom_polygon(data= states, aes(x = long, y = lat, group = group), 
               fill="transparent",color = "black", linewidth=0.5)+
  labs(title = "2010")

map2020<-ggplot(data = Yr2020) + 
  geom_point(data = Yr2020, aes(x = lake_lon_decdeg, y = lake_lat_decdeg), 
             color = Yr2020$col_hex, size = 1) +  # Add points
  scale_fill_distiller( palette="Spectral", direction=1)+
  theme_void()+
  coord_fixed(1.3) +
  geom_polygon(data= states, aes(x = long, y = lat, group = group), 
               fill="transparent",color = "black", linewidth=0.5)+
  labs(title = "2020")

require(gridExtra)
require(grid)
mapcombined<-arrangeGrob(map1990, map2000, map2010,map2020)
grid.draw(mapcombined)
ggsave("mapcombined.jpg", mapcombined, height=12, width=12, dpi=300)

```

