---
title: "LakeColor_Spatial"
author: "Jordan Von Eggers"
date: "2023-04-13"
output: html_document
editor_options: 
  chunk_output_type: console
---


#for Jordan

```{r}

require(stringr)

require(tidyverse)
landcover_data <- readRDS('landcover_data.RDS')
mast<-readRDS("masterDF.RDS")
intermountain<-mast[mast$lake_centroidstate%in%c("ID","MT", "WY", "CO"),]
intermountain<-intermountain[intermountain$year==2021,]

HUC_zoneid<-intermountain$hu12_zoneid

tmp<-as.data.frame(HUC_zoneid)
tmp<-str_split_fixed(tmp[,1],"_",n=2)[,2]

landcover_data<-landcover_data[landcover_data$zoneid %in% HUC_zoneid,]

landcover_data<-landcover_data[landcover_data$spatial_division=="hu12",]

sub<-landcover_data[,6:21]

landcover_data<-sub %>%
  mutate(dom_landcover = names(.)[max.col(.)])

write.csv(landcover_data, "landcover_subset.csv")
```



```{bash}
rsync jvonegge@beartooth.arcc.uwyo.edu:/project/seddna/jvonegge/LakeColorData/Data/landcover_subset.csv /Users/jordanscheibe/Desktop/
```




```{bash}
rsync -a /Users/jordanscheibe/Desktop/Data2 jvonegge@beartooth.arcc.uwyo.edu:/project/seddna/jvonegge/

/Users/jordanscheibe/Desktop/Data2

salloc --mem=120GB --nodes=1 --account=microbiome --time=3:00:00
module load arcc/1.0  gcc/12.2.0
module load r/4.2.2
R



```


```{r}
require(tidyverse)
limnoSat <- read.csv('Data/limnoSat_westernUSA.csv')
limnoSatMetadata <- read.csv('Data/limnoSat_westernUSA_metadata.csv')

climate_data <- readRDS('Data/climate_data.rds') #rename zone id to match whatever in this
landcover_data <- readRDS('Data/landcover_data.RDS')

elev_data <- readRDS('Data/elev_data.RDS')
hydro_data <- readRDS('Data/hydro_data.RDS')
watershed_data <- readRDS('Data/watershed_data.RDS')

source('Data/LAGOSUS_zoneIDs.R')

rm(infile1)
rm(inUrl1)



hydro2 <- hydro_data |>
  select(lagoslakeid, lake_waterarea_ha, lake_perimeter_m, lake_islandperimeter_m, lake_connectivity_class, lake_connectivity_permanent) |>
  mutate(lake_totalperimeter_m = lake_islandperimeter_m + lake_perimeter_m)

elev2 <- elev_data |>
  select(lagoslakeid, lake_elevation_m, lake_county)

limnoSat2 <- limnoSat |>
  select(-nhdplusv2_comid)

watershed2 <- watershed_data |>
  select(lagoslakeid, ws_area_ha, ws_lake_arearatio)

zoneid2 <- zoneIDs |>
  select(lagoslakeid, hu12_zoneid)


bigdata <- left_join(limnoSat, hydro2) |>
  left_join(elev2) |>
  left_join(watershed2) |>
  left_join(zoneid2)

bigdata2 <- bigdata |>
  filter(lake_waterarea_ha < 10)


# length(unique(bigdata2$lagoslakeid))
# 
# 
# climate2 <- climate_data |>
#   rename(hu12_zoneid = zoneid) |>
#   select(-spatial_division)
# 
# 
# bigdata3 <- left_join(bigdata2, climate2)


saveRDS(bigdata2, 'Data/masterDF.RDS')


```


```{bash}
rsync jvonegge@beartooth.arcc.uwyo.edu:/project/seddna/jvonegge/LakeColorData/Data/masterDF.RDS /Users/jordanscheibe/Desktop/
  

rsync jvonegge@beartooth.arcc.uwyo.edu:/project/seddna/jvonegge/LakeColorData/masterDF.csv /Users/jordanscheibe/Desktop/
```

#read in data
```{r}
mast<-readRDS("/Users/jordanscheibe/Desktop/masterDF.RDS")
```


#Looking at intermountain west

```{r}
require(tidyverse)
require(geosphere)
intermountain<-mast[mast$lake_centroidstate%in%c("ID","MT", "WY", "CO"),]
intermountain<-intermountain[intermountain$year==2021,]

xy <- data.frame(X =intermountain$lake_lon_decdeg, Y = intermountain$lake_lat_decdeg, lakeID=intermountain$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")




pairwise<-dist_m

sub1<-intermountain[,names(intermountain) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

conn_type<-intermountain[,names(intermountain) %in% c("lagoslakeid","lake_connectivity_class")]
conn_type<-unique(conn_type)

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub2<-merge(sub2,conn_type, by= "lagoslakeid")
sub3<-sub2

names(sub2)<-c("lake1","dWL_1","landcover1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2","landcover2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)
pairwise$sameconnclass<-rep(NA, nrow(pairwise))
pairwise[pairwise$landcover1==pairwise$landcover2,]$sameconnclass<-"1"
pairwise[pairwise$landcover1!=pairwise$landcover2,]$sameconnclass<-"0"


pairwise$color_simm<-rep(NA, nrow(pairwise))
pairwise[pairwise$diff_dWL<=10,]$color_simm<-"low"
pairwise[pairwise$diff_dWL>10 & pairwise$diff_dWL<=30,]$color_simm<-"med_low"
pairwise[pairwise$diff_dWL>30 & pairwise$diff_dWL<=50,]$color_simm<-"med_high"
pairwise[pairwise$diff_dWL>50,]$color_simm<-"high"
head(pairwise)
```

```{r}
head(pairwise)

levels<-c("low","med_low","med_high","high")
i=1
sameconnpercent<-NULL
for(i in 1:4){

tmp<-pairwise[pairwise$color_simm==levels[i],]

sameconnpercent<-c(sameconnpercent,(nrow(tmp[tmp$landcover2==tmp$landcover1,])/nrow(tmp)))
}
df<-as.data.frame(same=sameconnpercent)

```

#elevation
Testing if there are differences in elevation and color
```{r}

sub1<-intermountain[,names(intermountain) %in% c("lagoslakeid","lake_elevation_m")]
sub1<-unique(sub1)


sub2<-sub1
sub3<-sub1
names(sub2)<-c("lake1","elev_1")
names(sub3)<-c("lake2","elev_2")

pairwise$lake2<-str_split_fixed(pairwise$lake2,"_",n=2)[,2]
pairwise$lake1<-str_split_fixed(pairwise$lake1,"_",n=2)[,2]

sub2$lake1<-as.character(sub2$lake1)
sub3$lake2<-as.character(sub3$lake2)

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)
pairwise$diff_elev<-abs(pairwise$elev_1-pairwise$elev_2)

plot(pairwise$diff_elev,pairwise$diff_dWL, pch=16, col="#00000050", ylab="Difference in color (dWL)", xlab="Difference in elevation (m)")

abline(lm(pairwise_far$diff_dWL~pairwise$diff_elev), col="red")
summary(lm(pairwise_far$diff_dWL~pairwise$diff_elev))


```




add in landcover - this did not work
```{r}

landcov<-read.csv("/Users/jordanscheibe/Desktop/landcover_subset.csv")
names(landcov)[1]<-"hu12_zoneid"
landcov<-landcov[,names(landcov)%in% c("hu12_zoneid","dom_landcover")]
landcov$hu12_zoneid<-paste("hu12",landcov$hu12_zoneid, sep="_")


#add in hu12 ID into the pairwise df

pairwise$lake2<-str_split_fixed(pairwise$lake2,"_",n=2)[,2]
pairwise$lake1<-str_split_fixed(pairwise$lake1,"_",n=2)[,2]
head(pairwise)

intermountain<-mast[mast$lake_centroidstate%in%c("ID","MT", "WY", "CO"),]
intermountain<-intermountain[intermountain$year==2021,]

HUC_zoneid<-intermountain[,colnames(intermountain)%in%c("hu12_zoneid","lagoslakeid")]
HUC_zoneid<-unique(HUC_zoneid)

table(HUC_zoneid$hu12_zoneid%in%landcov$hu12_zoneid)
table(landcov$hu12_zoneid %in%HUC_zoneid$hu12_zoneid)
HUC_zoneid$hu12_zoneid<-as.character(HUC_zoneid$hu12_zoneid)
domhuclago<-merge(HUC_zoneid,landcov, by="hu12_zoneid")



pairwise_lc<-merge(pairwise, HUC_zoneid, by="hu12_zoneid")

```


same watershed
```{r}
same<-pairwise[pairwise$sameconnclass=="y",]

pairwise[pairwise$landcover1==pairwise$landcover2,]$sameconnclass<-"low"
pairwise[pairwise$landcover1!=pairwise$landcover2,]$sameconnclass<-"n"



plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

pairwise_far<-pairwise[pairwise$dist_km>1000,]
plot(pairwise_far$dist_km, pairwise_far$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise_far$diff_dWL~pairwise_far$dist_km), col="red")
summary(lm(pairwise_far$diff_dWL~pairwise_far$dist_km))




blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
≈

green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")

```


#Looping for comparisons of all Western States

```{r}
mat<-matrix(1:121,byrow=T,nrow=11,ncol=11)
colnames(mat)<-unique(mast$lake_centroidstate)
rownames(mat)<-unique(mast$lake_centroidstate)
mat[upper.tri(mat, diag = T)] <- NA
mat<-as.data.frame(mat)

allstatecomps<-data.frame(t(combn(names(mat),2)), dist=t(mat)[upper.tri(mat)])

allstatecomps$dist<-NULL
rm(mat)

st_comps<-list()
for(i in 1:nrow(allstatecomps)){
  st_comps[[i]]<-c(allstatecomps$X1[i],allstatecomps$X2[i])
}
```



#






```{r}
i=1
y=1
year<-c(1991,2021)
for(i in 1:55){
df1<-mast[mast$lake_centroidstate%in%c(st_comps[[i]]),]

for(y in 1:2){
df2<-df1[df1$year==year[y],]

xy <- data.frame(X =df2$lake_lon_decdeg, Y = df2$lake_lat_decdeg, lakeID=df2$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL

dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)

dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-df2[,names(df2) %in% c("lagoslakeid","dWL")]

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

pairwise_far<-pairwise[pairwise$dist_km>1000,]
plot(pairwise_far$dist_km, pairwise_far$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise_far$diff_dWL~pairwise_far$dist_km), col="red")
summary(lm(pairwise_far$diff_dWL~pairwise_far$dist_km))
  
}
}
```







#Not as clean
## filter by WY
```{r}
WY<-mast[mast$lake_centroidstate=="WY",]
WY_2021<-WY[WY$year==2021,]
WY_2019<-WY[WY$year==2019,]
WY_1991<-WY[WY$year==1991,]

length(unique(WY_2021$lagoslakeid))
unique(mast$year)

require(geosphere)
require(reshape2)


xy <- data.frame(X =WY_2021$lake_lon_decdeg, Y = WY_2021$lake_lat_decdeg, lakeID=WY_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-WY_2021[,names(WY_2021) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)




plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")

blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")

```



# filter by CA
```{r}
CA<-mast[mast$lake_centroidstate=="CA",]
CA_2021<-CA[CA$year==2021,]
CA_2019<-CA[CA$year==2019,]
CA_1991<-CA[CA$year==1991,]

length(unique(CA_2021$lagoslakeid))
unique(mast$year)

xy <- data.frame(X =CA_2021$lake_lon_decdeg, Y = CA_2021$lake_lat_decdeg, lakeID=CA_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-CA_2021[,names(CA_2021) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")

blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")
```

```{r}
WYNV<-mast[mast$lake_centroidstate%in%c("WY","NV"),]
WYNV_2021<-WYNV[WYNV$year==2021,]

length(unique(WYNV_2021$lagoslakeid))
unique(mast$year)

xy <- data.frame(X =WYNV_2021$lake_lon_decdeg, Y = WYNV_2021$lake_lat_decdeg, lakeID=WYNV_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-WYNV_2021[,names(WYNV_2021) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")
```


#filter by WY NV, in past
```{r}
WYNV<-mast[mast$lake_centroidstate%in%c("WY","NV"),]
WYNV_2021<-WYNV[WYNV$year==1991,]

length(unique(WYNV_2021$lagoslakeid))
unique(mast$year)

xy <- data.frame(X =WYNV_2021$lake_lon_decdeg, Y = WYNV_2021$lake_lat_decdeg, lakeID=WYNV_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-WYNV_2021[,names(WYNV_2021) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")
```


```{r}
WYNV<-mast[mast$lake_centroidstate%in%c("WY","NV"),]
WYNV_2021<-WYNV[WYNV$year==2021,]

length(unique(WYNV_2021$lagoslakeid))
unique(mast$year)

xy <- data.frame(X =WYNV_2021$lake_lon_decdeg, Y = WYNV_2021$lake_lat_decdeg, lakeID=WYNV_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m



sub1<-WYNV_2021[,names(WYNV_2021) %in% c("lagoslakeid","dWL", "lake_elevation_m")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub2<-inner_join(sub2,tmp)
sub3<-sub2


names(sub2)<-c("lake1","dWL_1","elev_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2","elev_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)
pairwise$diff_elev<-abs(pairwise$elev_2-pairwise$elev_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")
```



```{r}
IDAZ<-mast[mast$lake_centroidstate%in%c("ID","AZ"),]
IDAZ_2021<-IDAZ[IDAZ$year==1991,]

length(unique(IDAZ_2021$lagoslakeid))
unique(mast$year)

xy <- data.frame(X =IDAZ_2021$lake_lon_decdeg, Y = IDAZ_2021$lake_lat_decdeg, lakeID=IDAZ_2021$lagoslakeid)
xy<-unique(xy)
rownames(xy)<-paste("A",xy$lakeID, sep="_")
xy$lakeID<-NULL


dist_m_output<-distm(xy)

dist_m_output<-as.data.frame(dist_m_output)
rownames(dist_m_output)<-rownames(xy)
names(dist_m_output)<-rownames(xy)

geo_dist<-as.dist(dist_m_output)


dist_m_output[upper.tri(dist_m_output, diag = T)] <- NA

dist_m<-data.frame(t(combn(names(dist_m_output),2)), dist=t(dist_m_output)[upper.tri(dist_m_output)] )

dist_m$dist_km<-dist_m$dist/1000

names(dist_m)<-c("lake1","lake2","dist_m","dist_km")
pairwise<-dist_m

sub1<-IDAZ_2021[,names(IDAZ_2021) %in% c("lagoslakeid","dWL")]
length(unique(sub1$lagoslakeid))

sub2<-sub1 %>% group_by(lagoslakeid) %>% summarise(dWL=median(dWL,na.rm=T))
sub3<-sub2

names(sub2)<-c("lake1","dWL_1")
sub2$lake1<-paste("A",sub2$lake1, sep="_")
names(sub3)<-c("lake2","dWL_2")
sub3$lake2<-paste("A",sub3$lake2, sep="_")

pairwise<-inner_join(sub2,pairwise)
pairwise<-inner_join(sub3,pairwise)

pairwise$diff_dWL<-abs(pairwise$dWL_2-pairwise$dWL_1)


plot(pairwise$dist_km, pairwise$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise$diff_dWL~pairwise$dist_km), col="red")
summary(lm(pairwise$diff_dWL~pairwise$dist_km))

pairwise_far<-pairwise[pairwise$dist_km>1000,]
plot(pairwise_far$dist_km, pairwise_far$diff_dWL, ylab="Difference in lake color", xlab="Distance (km)")
abline(lm(pairwise_far$diff_dWL~pairwise_far$dist_km), col="red")
summary(lm(pairwise_far$diff_dWL~pairwise_far$dist_km))




blue<-pairwise[pairwise$dWL_1<530 & pairwise$dWL_2<530,]

plot(blue$dist_km, blue$diff_dWL, ylab="Difference in lake color of blue", xlab="Distance (km)")
abline(lm(blue$diff_dWL~blue$dist_km), col="red")


green<-pairwise[pairwise$dWL_1>530 & pairwise$dWL_2>530,]

plot(green$dist_km, green$diff_dWL, ylab="Difference in lake color of green", xlab="Distance (km)")
abline(lm(green$diff_dWL~green$dist_km), col="red")
```




